int printf(char *fmt);
int puts(char *s);
int putchar(int c);
int putc(int c);
int getchar(void);
FILE *fopen(char *path, char *mode);
int fclose(FILE *fp);
int fgetc(FILE *fp);
int fputc(int c, FILE *fp);
int fputs(char *s, FILE *fp);
char *fgets(char *buf, int n, FILE *fp);
int fread(char *ptr, int size, int nmemb, FILE *fp);
int fwrite(char *ptr, int size, int nmemb, FILE *fp);
int fseek(FILE *fp, int off, int whence);
int ftell(FILE *fp);
int feof(FILE *fp);
int ferror(FILE *fp);
int fflush(FILE *fp);
int kbhit(void);
