#!/usr/bin/env python3
"""arch/m68k-mega: kernel.bin -> rom.h (Mega スケッチに #include させる PROGMEM 配列)

既存の d:\\ドキュメント\\Arduino\\MEGA2560_68000_DTACK_TEST\\rom.h と同じ形式で吐く。
ROM_START_PC はイメージ先頭のベクタ1(オフセット4, 初期PC)から読み取る
(crt0.s の _vectors がリンカ解決値を書いているのでここから逆算できる)。

使い方: python3 bin2romh.py kernel.bin rom.h
"""
import sys
import struct


def main():
    if len(sys.argv) != 3:
        print(f"usage: {sys.argv[0]} kernel.bin rom.h", file=sys.stderr)
        return 1

    with open(sys.argv[1], "rb") as f:
        data = f.read()

    if len(data) < 8:
        print("kernel.bin too small (missing vector table)", file=sys.stderr)
        return 1

    start_pc = struct.unpack(">I", data[4:8])[0]

    with open(sys.argv[2], "w") as out:
        out.write("#ifndef ROM_H\n#define ROM_H\n#include <avr/pgmspace.h>\n\n")
        out.write("#define ROM_LOAD_ADDR 0x00000000UL\n")
        out.write(f"#define ROM_START_PC 0x{start_pc:08X}UL\n\n")
        out.write("/* generated by arch/m68k-mega/tools/bin2romh.py from kernel.bin. "
                   "編集しないこと。 */\n")
        out.write("const uint8_t rom_1[] PROGMEM = {\n")
        for i in range(0, len(data), 12):
            row = data[i:i + 12]
            out.write("  " + ", ".join(f"0x{b:02x}" for b in row) + ",\n")
        out.write("};\n\n#endif\n")

    print(f"wrote {sys.argv[2]}: {len(data)} bytes, start_pc=0x{start_pc:08X}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
