; Generated by TzCC
    .area _CODE

_main::
    ld ix, #0
    add ix, sp
    ld l, 2(ix)
    ld h, 3(ix)
    ld (var_argc), hl
    ld l, 4(ix)
    ld h, 5(ix)
    ld (var_argv), hl
    ld hl, #str_24909232
    push hl
    call _printf
    pop af
    ld hl, #0
    ret

    .area _DATA
var_argc:
    .dw 0
var_argv:
    .dw 0
str_24909232:
    .ascii "Hello TzCC"
    .db 0
