; Generated by TzCC
    .area _CODE

_get_greeting::
    ld ix, #0
    add ix, sp
    ld l, 2(ix)
    ld h, 3(ix)
    ld (var_name), hl
    ld hl, #str_25675184
    ret
_print_both::
    ld ix, #0
    add ix, sp
    ld l, 2(ix)
    ld h, 3(ix)
    ld (var_str1), hl
    ld l, 4(ix)
    ld h, 5(ix)
    ld (var_str2), hl
    ld hl, (var_str1)
    push hl
    call _printf
    pop af
    ld hl, (var_str2)
    push hl
    call _printf
    pop af
    ret
_main::
    ld ix, #0
    add ix, sp
    ld l, 2(ix)
    ld h, 3(ix)
    ld (var_argc), hl
    ld l, 4(ix)
    ld h, 5(ix)
    ld (var_argv), hl
    ld hl, #str_25677152
    push hl
    call _get_greeting
    pop af
    ld (var_g), hl
    ld hl, #var_msg
    push hl
    ld hl, (var_g)
    push hl
    call _print_both
    pop af
    pop af
    ld hl, #0
    ret

    .area _DATA
var_name:
    .dw 0
str_25675184:
    .ascii "Hello "
    .db 0
var_str1:
    .dw 0
var_str2:
    .dw 0
var_argc:
    .dw 0
var_argv:
    .dw 0
var_g:
    .dw 0
str_25677152:
    .ascii "test"
    .db 0
var_msg:
    .ascii "TzCC"
    .db 10
    .ascii ""
    .db 0
