; Generated by TzCC
    .area _CODE

_main::
    ld ix, #0
    add ix, sp
    ld l, 2(ix)
    ld h, 3(ix)
    ld (var_argc), hl
    ld l, 4(ix)
    ld h, 5(ix)
    ld (var_argv), hl
    ld hl, #str_28657072
    ld (var_msg), hl
    ld hl, (var_msg)
    push hl
    call _puts
    pop af
    ld hl, #0
    ret

    .area _DATA
var_argc:
    .dw 0
var_argv:
    .dw 0
var_msg:
    .dw str_28657072
str_28657072:
    .ascii "LibTest"
    .db 10
    .ascii ""
    .db 0
