; Generated by TzCC
    .area _CODE

_main::
    ld ix, #0
    add ix, sp
    ld l, 2(ix)
    ld h, 3(ix)
    ld (var_argc), hl
    ld l, 4(ix)
    ld h, 5(ix)
    ld (var_argv), hl
    ld a, #65
    ld (var_c), a
    ld a, (var_c)
    ld l, a
    ld h, #0
    push hl
    call _putc
    pop af
    ld hl, #0
    ret

    .area _DATA
var_argc:
    .dw 0
var_argv:
    .dw 0
var_c:
    .db 0
