; Generated by TzCC
    .area _CODE

_main::
    ld ix, #0
    add ix, sp
    ld l, 2(ix)
    ld h, 3(ix)
    ld (var_argc), hl
    ld l, 4(ix)
    ld h, 5(ix)
    ld (var_argv), hl
    ld hl, #str_22333152
    push hl
    ld hl, #str_22333040
    push hl
    call _fopen
    pop af
    pop af
    ld (var_f), hl
    ld hl, (var_f)
    push hl
    ld hl, #str_22333408
    push hl
    call _fputs
    pop af
    pop af
    ld hl, (var_f)
    push hl
    call _fclose
    pop af
    ld hl, #0
    ret

    .area _DATA
var_argc:
    .dw 0
var_argv:
    .dw 0
var_f:
    .dw 0
str_22333040:
    .ascii "test.txt"
    .db 0
str_22333152:
    .ascii "w"
    .db 0
str_22333408:
    .ascii "File IO Test"
    .db 10
    .ascii ""
    .db 0
