; Generated by TzCC
    .area _CODE

_main::
    ld ix, #0
    add ix, sp
    ld l, 2(ix)
    ld h, 3(ix)
    ld (var_argc), hl
    ld l, 4(ix)
    ld h, 5(ix)
    ld (var_argv), hl
    ld hl, #str_34449072
    ld (var_str1), hl
    ld a, #72
    ld (var_a), a
    ld a, (var_a)
    ld l, a
    ld h, #0
    push hl
    call _putc
    pop af
    ld a, #101
    ld (var_a), a
    ld a, (var_a)
    ld l, a
    ld h, #0
    push hl
    call _putc
    pop af
    ld hl, (var_str1)
    push hl
    call _printf
    pop af
    ld hl, #var_str2
    push hl
    call _printf
    pop af
    ld hl, #0
    ret

    .area _DATA
var_argc:
    .dw 0
var_argv:
    .dw 0
var_a:
    .db 0
var_str1:
    .dw str_34449072
str_34449072:
    .ascii "llo "
    .db 0
var_str2:
    .ascii "TzCC"
    .db 10
    .ascii ""
    .db 0
