; Generated by TzCC
    .area _CODE

_main::
    ld ix, #0
    add ix, sp
    ld l, 2(ix)
    ld h, 3(ix)
    ld (var_argc), hl
    ld l, 4(ix)
    ld h, 5(ix)
    ld (var_argv), hl
    ld hl, #str_20998432
    ld (var_s1), hl
    ld hl, #str_20998688
    ld (var_s2), hl
    ld hl, (var_s1)
    push hl
    ld hl, #var_buffer
    push hl
    call _strcpy
    pop af
    pop af
    ld hl, (var_s2)
    push hl
    ld hl, #var_buffer
    push hl
    call _strcat
    pop af
    pop af
    ld hl, #var_buffer
    push hl
    call _puts
    pop af
    ld hl, #0
    ret

    .area _DATA
var_argc:
    .dw 0
var_argv:
    .dw 0
var_s1:
    .dw str_20998432
str_20998432:
    .ascii "Hello "
    .db 0
var_s2:
    .dw str_20998688
str_20998688:
    .ascii "TzCC"
    .db 0
var_buffer:
    .ds 32
