; Generated by TzCC
    .area _CODE

_main::
    ld ix, #0
    add ix, sp
    ld l, 2(ix)
    ld h, 3(ix)
    ld (var_argc), hl
    ld l, 4(ix)
    ld h, 5(ix)
    ld (var_argv), hl
    ld hl, #0
    push hl
    ld hl, #1
    push hl
    ld hl, #2
    push hl
    call _socket
    pop af
    pop af
    pop af
    ld (var_fd), hl
    ld hl, #10
    push hl
    ld hl, #str_24297760
    push hl
    ld hl, (var_fd)
    push hl
    call _send
    pop af
    pop af
    pop af
    ld hl, #0
    ret

    .area _DATA
var_argc:
    .dw 0
var_argv:
    .dw 0
var_fd:
    .dw 0
str_24297760:
    .ascii "Socket OK"
    .db 10
    .ascii ""
    .db 0
