; Generated by TzCC
    .area _CODE

_main::
    ld ix, #0
    add ix, sp
    ld l, 2(ix)
    ld h, 3(ix)
    ld (var_argc), hl
    ld l, 4(ix)
    ld h, 5(ix)
    ld (var_argv), hl
    ld hl, #9
    push hl
    ld hl, #65
    push hl
    ld hl, #var_buf
    push hl
    call _memset
    pop af
    pop af
    pop af
    ld hl, #var_buf
    push hl
    call _puts
    pop af
    ld hl, #8
    push hl
    ld hl, #var_src
    push hl
    ld hl, #var_dst
    push hl
    call _memcpy
    pop af
    pop af
    pop af
    ld hl, #var_dst
    push hl
    call _puts
    pop af
    ld hl, #0
    ret

    .area _DATA
var_argc:
    .dw 0
var_argv:
    .dw 0
var_buf:
    .ds 10
var_src:
    .ascii "CopyTest"
    .db 0
var_dst:
    .ds 10
