; Generated by TzCC
    .area _CODE

_main::
    ld ix, #0
    add ix, sp
    ld l, 2(ix)
    ld h, 3(ix)
    ld (var_argc), hl
    ld l, 4(ix)
    ld h, 5(ix)
    ld (var_argv), hl
    ld hl, #str_21064176
    push hl
    ld hl, #str_21064064
    push hl
    call _fopen
    pop af
    pop af
    ld (var_fw), hl
    ld hl, (var_fw)
    push hl
    ld hl, #str_21064432
    push hl
    call _fputs
    pop af
    pop af
    ld hl, (var_fw)
    push hl
    call _fclose
    pop af
    ld hl, #str_21065376
    push hl
    ld hl, #str_21065264
    push hl
    call _fopen
    pop af
    pop af
    ld (var_fr), hl
    ld hl, (var_fr)
    push hl
    ld hl, #32
    push hl
    ld hl, #var_buf
    push hl
    call _fgets
    pop af
    pop af
    pop af
    ld hl, #var_buf
    push hl
    call _puts
    pop af
    ld hl, (var_fr)
    push hl
    call _fclose
    pop af
    ld hl, #0
    ret

    .area _DATA
var_argc:
    .dw 0
var_argv:
    .dw 0
var_buf:
    .ds 32
var_fw:
    .dw 0
str_21064064:
    .ascii "io.txt"
    .db 0
str_21064176:
    .ascii "w"
    .db 0
str_21064432:
    .ascii "File IO Test"
    .db 10
    .ascii ""
    .db 0
var_fr:
    .dw 0
str_21065264:
    .ascii "io.txt"
    .db 0
str_21065376:
    .ascii "r"
    .db 0
