; Generated by TzCC
    .area _CODE

_main::
    ld ix, #0
    add ix, sp
    ld l, 2(ix)
    ld h, 3(ix)
    ld (var_argc), hl
    ld l, 4(ix)
    ld h, 5(ix)
    ld (var_argv), hl
    ld hl, #3
    ld (var_a), hl
    ld hl, #5
    ld (var_b), hl
    ld hl, #0
    ld (var_r), hl
    ld hl, (var_a)
    push hl
    ld hl, (var_b)
    pop de
    ex de, hl
    or a
    sbc hl, de
    ld hl, #1
    jr c, Lcmp0
    ld hl, #0
Lcmp0:
    ld (var_r), hl
    ld hl, (var_a)
    push hl
    ld hl, (var_b)
    pop de
    or a
    sbc hl, de
    ld hl, #1
    jr c, Lcmp1
    ld hl, #0
Lcmp1:
    ld (var_r), hl
    ld hl, (var_a)
    push hl
    ld hl, #3
    pop de
    or a
    sbc hl, de
    ld hl, #0
    jr c, Lcmp2
    ld hl, #1
Lcmp2:
    ld (var_r), hl
    ld hl, (var_b)
    push hl
    ld hl, #6
    pop de
    ex de, hl
    or a
    sbc hl, de
    ld hl, #0
    jr c, Lcmp3
    ld hl, #1
Lcmp3:
    ld (var_r), hl
    ld hl, (var_a)
    push hl
    ld hl, #3
    pop de
    ex de, hl
    or a
    sbc hl, de
    ld hl, #1
    jr z, Lcmp4
    ld hl, #0
Lcmp4:
    ld (var_r), hl
    ld hl, (var_a)
    push hl
    ld hl, (var_b)
    pop de
    ex de, hl
    or a
    sbc hl, de
    ld hl, #0
    jr z, Lcmp5
    ld hl, #1
Lcmp5:
    ld (var_r), hl
    ld hl, (var_r)
    ld a, h
    or l
    ld hl, #1
    jr z, Lnot6
    ld hl, #0
Lnot6:
    ld (var_r), hl
    ld hl, (var_a)
    ex de, hl
    ld hl, #0
    or a
    sbc hl, de
    ld (var_r), hl
    ld hl, (var_a)
    push hl
    ld hl, (var_b)
    push hl
    ld hl, #2
    pop de
    call _mul
    pop de
    add hl, de
    ld (var_r), hl
    ld hl, (var_a)
    push hl
    ld hl, (var_b)
    pop de
    ex de, hl
    or a
    sbc hl, de
    ld hl, #1
    jr c, Lcmp8
    ld hl, #0
Lcmp8:
    ld a, h
    or l
    jp z, Lelse7
    ld hl, #str_10800544
    push hl
    call _printf
    pop af
    jp Lend7
Lelse7:
    ld hl, #str_10800880
    push hl
    call _printf
    pop af
Lend7:
    ld hl, #0
    ret

    .area _DATA
var_argc:
    .dw 0
var_argv:
    .dw 0
var_a:
    .dw 0
var_b:
    .dw 0
var_r:
    .dw 0
str_10800544:
    .ascii "less"
    .db 10
    .ascii ""
    .db 0
str_10800880:
    .ascii "not less"
    .db 10
    .ascii ""
    .db 0
