; Generated by TzCC
    .area _CODE

_main::
    ld ix, #0
    add ix, sp
    ld l, 2(ix)
    ld h, 3(ix)
    ld (var_argc), hl
    ld l, 4(ix)
    ld h, 5(ix)
    ld (var_argv), hl
    ld hl, #str_35465856
    push hl
    call _atoi
    pop af
    ld (var_val), hl
    ld hl, #50
    ex de, hl
    ld hl, #0
    or a
    sbc hl, de
    ld (var_neg), hl
    ld hl, (var_neg)
    push hl
    call _abs
    pop af
    ld (var_res), hl
    ld hl, #0
    ret

    .area _DATA
var_argc:
    .dw 0
var_argv:
    .dw 0
var_val:
    .dw 0
str_35465856:
    .ascii "123"
    .db 0
var_neg:
    .dw 0
var_res:
    .dw 0
