; Generated by TzCC
    .area _CODE

_main::
    ld ix, #0
    add ix, sp
    ld l, 2(ix)
    ld h, 3(ix)
    ld (var_argc), hl
    ld l, 4(ix)
    ld h, 5(ix)
    ld (var_argv), hl
    ld hl, #str_27384384
    push hl
    ld hl, #str_27384272
    push hl
    call _fopen
    pop af
    pop af
    ld (var_f), hl
    ld hl, (var_f)
    push hl
    call _fgetc
    pop af
    ld (var_c), hl
    ld hl, (var_c)
    push hl
    call _putc
    pop af
    ld hl, (var_f)
    push hl
    call _fclose
    pop af
    ld hl, #str_27385648
    push hl
    call _puts
    pop af
    ld hl, #0
    ret

    .area _DATA
var_argc:
    .dw 0
var_argv:
    .dw 0
var_f:
    .dw 0
str_27384272:
    .ascii "test.txt"
    .db 0
str_27384384:
    .ascii "r"
    .db 0
var_c:
    .dw 0
str_27385648:
    .ascii ""
    .db 10
    .ascii ""
    .db 0
