; Generated by TzCC
    .area _CODE

_main::
    ld ix, #0
    add ix, sp
    ld l, 2(ix)
    ld h, 3(ix)
    ld (var_argc), hl
    ld l, 4(ix)
    ld h, 5(ix)
    ld (var_argv), hl
    ld hl, (_stdout)
    ld (var_f1), hl
    ld hl, (_stderr)
    ld (var_f2), hl
    ld hl, (var_f1)
    push hl
    ld hl, #str_17811568
    push hl
    call _fputs
    pop af
    pop af
    ld hl, (var_f2)
    push hl
    ld hl, #str_17811968
    push hl
    call _fputs
    pop af
    pop af
    ld hl, (_stdin)
    push hl
    call _fgetc
    pop af
    ld a, l
    ld (var_c), a
    ld hl, (var_f1)
    push hl
    ld a, (var_c)
    ld l, a
    ld h, #0
    push hl
    call _fputc
    pop af
    pop af
    ld hl, #0
    ret

    .area _DATA
var_argc:
    .dw 0
var_argv:
    .dw 0
var_f1:
    .dw 0
var_f2:
    .dw 0
str_17811568:
    .ascii "Hello stdout!"
    .db 10
    .ascii ""
    .db 0
str_17811968:
    .ascii "Error stderr!"
    .db 10
    .ascii ""
    .db 0
var_c:
    .db 0
