; Generated by TzCC
    .area _CODE

_main::
    ld ix, #0
    add ix, sp
    ld l, 2(ix)
    ld h, 3(ix)
    ld (var_argc), hl
    ld l, 4(ix)
    ld h, 5(ix)
    ld (var_argv), hl
    ld hl, #2
    ld (var_n), hl
    ld hl, (var_n)
    push hl
    ld hl, #1
    pop de
    ex de, hl
    or a
    sbc hl, de
    ld hl, #1
    jr z, Lcmp1
    ld hl, #0
Lcmp1:
    ld a, h
    or l
    jp z, Lelse0
    ld hl, #str_29985120
    push hl
    call _puts
    pop af
    jp Lend0
Lelse0:
    ld hl, (var_n)
    push hl
    ld hl, #2
    pop de
    ex de, hl
    or a
    sbc hl, de
    ld hl, #1
    jr z, Lcmp3
    ld hl, #0
Lcmp3:
    ld a, h
    or l
    jp z, Lelse2
    ld hl, #str_29985872
    push hl
    call _puts
    pop af
    jp Lend2
Lelse2:
    ld hl, #str_29986208
    push hl
    call _puts
    pop af
Lend2:
Lend0:
    ld hl, (var_n)
    ld a, h
    or l
    jp z, Lend4
    ld hl, #str_29986688
    push hl
    call _puts
    pop af
Lend4:
    ld hl, (var_n)
    ld a, h
    or l
    ld hl, #1
    jr z, Lnot6
    ld hl, #0
Lnot6:
    ld a, h
    or l
    jp z, Lend5
    ld hl, #str_29987248
    push hl
    call _puts
    pop af
Lend5:
    ld hl, #0
    ret

    .area _DATA
var_argc:
    .dw 0
var_argv:
    .dw 0
var_n:
    .dw 0
str_29985120:
    .ascii "one"
    .db 0
str_29985872:
    .ascii "two"
    .db 0
str_29986208:
    .ascii "many"
    .db 0
str_29986688:
    .ascii "nonzero"
    .db 0
str_29987248:
    .ascii "zero"
    .db 0
