; Generated by TzCC
    .area _CODE

_main::
    ld ix, #0
    add ix, sp
    ld l, 2(ix)
    ld h, 3(ix)
    ld (var_argc), hl
    ld l, 4(ix)
    ld h, 5(ix)
    ld (var_argv), hl
    ld hl, #65
    ld (var_c), hl
Lbeg0:
    ld hl, (var_c)
    push hl
    ld hl, #69
    pop de
    or a
    sbc hl, de
    ld hl, #0
    jr c, Lcmp1
    ld hl, #1
Lcmp1:
    ld a, h
    or l
    jp z, Lend0
    ld hl, (var_c)
    push hl
    call _putchar
    pop af
    ld hl, (var_c)
    push hl
    ld hl, #1
    pop de
    add hl, de
    ld (var_c), hl
    jp Lbeg0
Lend0:
    ld hl, #10
    push hl
    call _putchar
    pop af
    ld hl, #0
    ret

    .area _DATA
var_argc:
    .dw 0
var_argv:
    .dw 0
var_c:
    .dw 0
