; Generated by TzCC
    .area _CODE

_main::
    ld ix, #0
    add ix, sp
    ld l, 2(ix)
    ld h, 3(ix)
    ld (var_argc), hl
    ld l, 4(ix)
    ld h, 5(ix)
    ld (var_argv), hl
    ld hl, #str_14535488
    push hl
    ld hl, #str_14535376
    push hl
    call _fopen
    pop af
    pop af
    ld (var_f), hl
    ld hl, (var_f)
    push hl
    ld hl, #0
    pop de
    ex de, hl
    or a
    sbc hl, de
    ld hl, #1
    jr z, Lcmp1
    ld hl, #0
Lcmp1:
    ld a, h
    or l
    jp z, Lend0
    ld hl, #str_14536240
    push hl
    call _printf
    pop af
    ld hl, #1
Lend0:
Lbeg2:
    ld hl, (var_f)
    push hl
    ld hl, #64
    push hl
    ld hl, #var_str
    push hl
    call _fgets
    pop af
    pop af
    pop af
    push hl
    ld hl, #0
    pop de
    ex de, hl
    or a
    sbc hl, de
    ld hl, #0
    jr z, Lcmp3
    ld hl, #1
Lcmp3:
    ld a, h
    or l
    jp z, Lend2
    ld hl, (_stdout)
    push hl
    ld hl, #var_str
    push hl
    call _fputs
    pop af
    pop af
    jp Lbeg2
Lend2:
    ld hl, (var_f)
    push hl
    call _fclose
    pop af
    ld hl, #0
    ret

    .area _DATA
var_argc:
    .dw 0
var_argv:
    .dw 0
var_str:
    .ds 64
var_f:
    .dw 0
str_14535376:
    .ascii "TEST.TXT"
    .db 0
str_14535488:
    .ascii "r"
    .db 0
str_14536240:
    .ascii "cannot open TEST.TXT"
    .db 10
    .ascii ""
    .db 0
