; Generated by TzCC
    .area _CODE

_add::
    ld ix, #0
    add ix, sp
    ld l, 2(ix)
    ld h, 3(ix)
    ld (var_a), hl
    ld l, 4(ix)
    ld h, 5(ix)
    ld (var_b), hl
    ld hl, (var_a)
    push hl
    ld hl, (var_b)
    pop de
    add hl, de
    ret
_main::
    ld ix, #0
    add ix, sp
    ld l, 2(ix)
    ld h, 3(ix)
    ld (var_argc), hl
    ld l, 4(ix)
    ld h, 5(ix)
    ld (var_argv), hl
    ld hl, #100
    push hl
    ld hl, #200
    push hl
    call _add
    pop af
    pop af
    ld (var_r), hl
    ld hl, #0
    ld (var_k), hl
    ld hl, #0
    ld (var_k), hl
Lbeg0:
    ld hl, (var_k)
    push hl
    ld hl, (var_r)
    pop de
    ex de, hl
    or a
    sbc hl, de
    ld hl, #1
    jr c, Lcmp1
    ld hl, #0
Lcmp1:
    ld a, h
    or l
    jp z, Lend0
    ld hl, #35
    push hl
    call _putchar
    pop af
    ld hl, (var_k)
    push hl
    ld hl, #100
    pop de
    add hl, de
    ld (var_k), hl
    jp Lbeg0
Lend0:
    ld hl, #10
    push hl
    call _putchar
    pop af
    ld hl, #0
    ret

    .area _DATA
var_a:
    .dw 0
var_b:
    .dw 0
var_argc:
    .dw 0
var_argv:
    .dw 0
var_r:
    .dw 0
var_k:
    .dw 0
