; Generated by TzCC
    .area _CODE

_main::
    ld ix, #0
    add ix, sp
    ld l, 2(ix)
    ld h, 3(ix)
    ld (var_argc), hl
    ld l, 4(ix)
    ld h, 5(ix)
    ld (var_argv), hl
    ld hl, #str_23115952
    push hl
    ld hl, #65
    push hl
    ld hl, #300
    push hl
    ld hl, #40000
    push hl
    ld hl, #300
    push hl
    ld hl, #str_23115392
    push hl
    call _printf
    pop af
    pop af
    pop af
    pop af
    pop af
    pop af
    ld hl, #0
    push hl
    ld hl, #5
    ex de, hl
    ld hl, #0
    or a
    sbc hl, de
    push hl
    ld hl, #str_23116208
    push hl
    call _printf
    pop af
    pop af
    pop af
    ld hl, #42
    push hl
    ld hl, #str_23116768
    push hl
    call _printf
    pop af
    pop af
    ld hl, #0
    ret

    .area _DATA
var_argc:
    .dw 0
var_argv:
    .dw 0
str_23115392:
    .ascii "d=%d u=%u x=%x c=%c s=%s %%"
    .db 10
    .ascii ""
    .db 0
str_23115952:
    .ascii "abc"
    .db 0
str_23116208:
    .ascii "neg=%d zero=%d"
    .db 10
    .ascii ""
    .db 0
str_23116768:
    .ascii "width ignored [%04d]"
    .db 10
    .ascii ""
    .db 0
