; tzcc --tizix-user : IY 相対 PIC へ変換済み
; Generated by TzCC
    .area _CODE

_main::
    ld ix, #0
    add ix, sp
    ld l, 2(ix)
    ld h, 3(ix)
    push af
    push bc
    ex de, hl
    ld hl, #var_argc
    push iy
    pop bc
    add hl, bc
    ld (hl), e
    inc hl
    ld (hl), d
    pop bc
    pop af
    ld l, 4(ix)
    ld h, 5(ix)
    push af
    push bc
    ex de, hl
    ld hl, #var_argv
    push iy
    pop bc
    add hl, bc
    ld (hl), e
    inc hl
    ld (hl), d
    pop bc
    pop af
    ld hl, #0
    push af
    push bc
    ex de, hl
    ld hl, #var_i
    push iy
    pop bc
    add hl, bc
    ld (hl), e
    inc hl
    ld (hl), d
    pop bc
    pop af
    ld hl, #0
    push af
    push bc
    ex de, hl
    ld hl, #var_i
    push iy
    pop bc
    add hl, bc
    ld (hl), e
    inc hl
    ld (hl), d
    pop bc
    pop af
Lbeg0:
    ld hl, #var_i
    push af
    push de
    push iy
    pop de
    add hl, de
    pop de
    pop af
    ld a, (hl)
    inc hl
    ld h, (hl)
    ld l, a
    push hl
    ld hl, #10
    pop de
    ex de, hl
    or a
    sbc hl, de
    ld hl, #1
    jr c, Lcmp1
    ld hl, #0
Lcmp1:
    ld a, h
    or l
    jr nz, Ltz100000
    push hl
    push af
    push de
    ld hl, #Lend0
    push iy
    pop de
    add hl, de
    pop de
    pop af
    ex (sp), hl
    ret
Ltz100000:
    ld hl, #48
    push hl
    ld hl, #var_i
    push af
    push de
    push iy
    pop de
    add hl, de
    pop de
    pop af
    ld a, (hl)
    inc hl
    ld h, (hl)
    ld l, a
    pop de
    add hl, de
    push hl
    push af
    push de
    ld hl, #_putchar
    push iy
    pop de
    add hl, de
    pop de
    pop af
    call ___sdcc_call_hl
    pop af
    ld hl, #var_i
    push af
    push de
    push iy
    pop de
    add hl, de
    pop de
    pop af
    ld a, (hl)
    inc hl
    ld h, (hl)
    ld l, a
    push hl
    ld hl, #1
    pop de
    add hl, de
    push af
    push bc
    ex de, hl
    ld hl, #var_i
    push iy
    pop bc
    add hl, bc
    ld (hl), e
    inc hl
    ld (hl), d
    pop bc
    pop af
    push hl
    push af
    push de
    ld hl, #Lbeg0
    push iy
    pop de
    add hl, de
    pop de
    pop af
    ex (sp), hl
    ret
Lend0:
    ld hl, #10
    push hl
    push af
    push de
    ld hl, #_putchar
    push iy
    pop de
    add hl, de
    pop de
    pop af
    call ___sdcc_call_hl
    pop af
    ld hl, #0
    ret

    .area _DATA
var_argc:
    .dw 0
var_argv:
    .dw 0
var_i:
    .dw 0
