; tzcc --tizix-user : IY 相対 PIC へ変換済み
; Generated by TzCC
    .area _CODE

_main::
    ld ix, #0
    add ix, sp
    ld l, 2(ix)
    ld h, 3(ix)
    push af
    push bc
    ex de, hl
    ld hl, #var_argc
    push iy
    pop bc
    add hl, bc
    ld (hl), e
    inc hl
    ld (hl), d
    pop bc
    pop af
    ld l, 4(ix)
    ld h, 5(ix)
    push af
    push bc
    ex de, hl
    ld hl, #var_argv
    push iy
    pop bc
    add hl, bc
    ld (hl), e
    inc hl
    ld (hl), d
    pop bc
    pop af
    ld hl, #79
    push hl
    push af
    push de
    ld hl, #_putchar
    push iy
    pop de
    add hl, de
    pop de
    pop af
    call ___sdcc_call_hl
    pop af
    ld hl, #75
    push hl
    push af
    push de
    ld hl, #_putchar
    push iy
    pop de
    add hl, de
    pop de
    pop af
    call ___sdcc_call_hl
    pop af
    ld hl, #10
    push hl
    push af
    push de
    ld hl, #_putchar
    push iy
    pop de
    add hl, de
    pop de
    pop af
    call ___sdcc_call_hl
    pop af
    ld hl, #0
    ret

    .area _DATA
var_argc:
    .dw 0
var_argv:
    .dw 0
