; Generated by TzCC
    .area _CODE

_main::
    ld hl, #1
    push hl
    ld hl, #2
    push hl
    ld hl, #3
    push hl
    call _mul
    pop af
    pop af
    push hl
    ld hl, #4
    push hl
    call _div
    pop af
    pop af
    pop de
    add hl, de
    push hl
    ld hl, #5
    pop de
    ex de, hl
    or a
    sbc hl, de
    ret

    .area _DATA
